version: 0.2

phases:
 
  build:
   
    commands:

    - echo "This is buid phase."
   
  post_build:
  
    commands:
     
    - echo "deployed to s3"

 artifacts:
   files:
    _ '**/*'
    base-directory: base_dir
    name: build-artifact-name
    discard-paths: no
